Repository Team-HGD/SniffMEET, pull requests merged in 2025-03, with the labels that each got.

#56 [feat/test] 산책로그 저장 / 불러오기 유즈케이스 구현
  SniffMeet/SNMPersistenceTests/FileManagerTest.swift
  SniffMeet/SNMSceneTests/WalkLogScene/WalkLogUsecaseTests.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/Core/Persistence/DataStoragable.swift
  SniffMeet/SniffMeet/Source/Core/Persistence/SNMFileManager.swift
  SniffMeet/SniffMeet/Source/Entity/WalkLog.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestWalkLogListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveWalkLogUseCase.swift
Labels: feature 🦖, test

#57 [feat] 산책 로그 저장 유즈케이스 연결
  SniffMeet/SniffMeet/Source/Common/Util/SNMErrorHandler.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Interactor/TrackWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Presenter/TrackWalkViewPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Router/TrackWalkRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/View/TrackWalkViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveWalkLogUseCase.swift
Labels: feature 🦖

#71 [fix/feat] ni없는 프로필 드랍 기능 디버깅 및 기능 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Interactor/ProfileDropInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Presenter/ProfileDropPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Router/ProfileDropRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/View/ConnectionState.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/View/ProfileDropViewController.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/LocalNetworkUseCase/TargetedProfileDropUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondUseCase/RespondMateRequestUseCase.swift
Labels: feature 🦖

#70 [fix] 산책 로그 뷰 UI 관련 수정
  SniffMeet/SNMSceneTests/LocalNetwork/MPCSessionConcurrencyTest.swift
  SniffMeet/SniffMeet/Source/Scene/Tab/TabBarModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/View/TrackWalkViewController.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/WalkLog/WalkLogList/Presenter/WalkLogListPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/WalkLog/WalkLogList/View/WalkLogListViewController.swift
Labels: UI/UX 🪄, bug fix 🛠️

#72 [feature] 프로필드랍 버튼 동작 개선
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Helper/HapticManager.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/ProfileDrop/Interactor/ProfileDropInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/ProfileDrop/Presenter/ProfileDropPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/ProfileDrop/Router/ProfileDropRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/ProfileDrop/View/ConnectionState.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/ProfileDrop/View/ProfileDropViewController.swift
Labels: feature 🦖

#63 [feat/ui] 로그인 뷰 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Assets.xcassets/appleSignIn.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/appleSignIn.imageset/appleSignIn.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/googleSignIn.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/googleSignIn.imageset/googleSignIn.png
  SniffMeet/SniffMeet/Source/Scene/Auth/SignIn/Interactor/SigninInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/SignIn/Presenter/SigninPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/SignIn/Router/SigninRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/SignIn/View/SigninViewController.swift
Labels: feature 🦖, UI/UX 🪄

#64 [feat/ui] 회원가입 뷰 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Scene/Auth/SignUp/Interactor/SignUpInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/SignUp/Presenter/SignUpPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/SignUp/Router/SignUpRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/SignUp/View/SignUpViewController.swift
Labels: feature 🦖, UI/UX 🪄

#65 [feat/ui] 비밀번호 재설정 화면 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Helper/RegexValidation.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/Interactor/ResetPwEmailInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/Interactor/ResetPwInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/Presenter/ResetPwEmailPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/Presenter/ResetPwPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/Router/ResetPwEmailRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/Router/ResetPwRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/View/ResetPwEmailViewController.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/ResetPw/View/ResetPwViewController.swift
Labels: feature 🦖, UI/UX 🪄

#81 [refactor] 프로젝트 내부 이미지 네이밍 통일
  SniffMeet/SNMSceneTests/MateListScene/UseCaseMock.swift
  SniffMeet/SNMSceneTests/WalkLogScene/WalkLogUsecaseTests.swift
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/Core/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/Core/Supabase/Storage/SupabaseStorageRequest.swift
  SniffMeet/SniffMeet/Source/Entity/DTO/DogProfileDTO.swift
  SniffMeet/SniffMeet/Source/Entity/DTO/UserInfoDTO.swift
  SniffMeet/SniffMeet/Source/Entity/Mate.swift
  SniffMeet/SniffMeet/Source/Entity/WalkLog.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/SetProfileInfo/Interactor/ProfileSetInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Home/EditProfile/Interactor/ProfileEditInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/ReportMate/Interactor/ReportMateInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/ReportMate/Presenter/ReportMatePresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/RequestMate/View/RequestMateViewController.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/RequestWalk/Interactor/RequestWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/RequestWalk/Presenter/RequestWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/RespondWalk/Interactor/ProcessedWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Interactor/TrackWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/WalkLog/WalkLogList/View/WalkLogListViewController.swift
  SniffMeet/SniffMeet/Source/Usecase/LocalNetworkUsecase/NearByProfileDropUsecase.swift
  SniffMeet/SniffMeet/Source/Usecase/LocalNetworkUsecase/TargetedProfileDropUsecase.swift
  SniffMeet/SniffMeet/Source/Usecase/RequestUsecase/LoadUserInfoUsecase.swift
  SniffMeet/SniffMeet/Source/Usecase/RequestUsecase/LoadUserProfileImageUsecase.swift
  SniffMeet/SniffMeet/Source/Usecase/RequestUsecase/RequestMateListUsecase.swift
  SniffMeet/SniffMeet/Source/Usecase/SaveUsecase/SaveProfileImageUsecase.swift
  SniffMeet/SniffMeet/Source/Usecase/SaveUsecase/SaveUserInfoUsecase.swift
  SniffMeet/SniffMeet/Source/Usecase/SaveUsecase/UpdateUserInfoUsecase.swift
Labels: redesign, refactor
