Repository Team-HGD/SniffMEET, pull requests merged in 2025-02, with the labels that each got.

#4 Refactor/#1/profile drop
  SniffMeet/SNMSceneTests/MateListScene/UseCaseMock.swift
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCAdvertiser.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCBroswer.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/NI/NIManager.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/UseCase/LocalNetworkUseCase/TryProfileDropUseCase.swift
Labels: refactor

#8 [feature] 메이트 삭제 및 신고 기능 구현
  SniffMeet/SNMSceneTests/MateListScene/MateListInteractorTests.swift
  SniffMeet/SNMSceneTests/MateListScene/MateListPresenterSpy.swift
  SniffMeet/SNMSceneTests/MateListScene/UseCaseMock.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + UITextViewDelegate.swift
  SniffMeet/SniffMeet/Source/DTO/ReportDTO.swift
  SniffMeet/SniffMeet/Source/Entity/Report.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/Interactor/ReportMateInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/Interactor/ReportPickerInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/Presenter/ReportMatePresenter.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/Presenter/ReportPickerPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/Router/ReportMateRouter.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/Router/ReportPickerRouter.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/View/ReportMateViewController.swift
  SniffMeet/SniffMeet/Source/Mate/ReportMate/View/ReportPickerViewController.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestReportUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/DeleteMateUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
Labels: feature

#14 [UI] 메이트 리스트 테이블 뷰 셀 악세사리 제거
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
Labels: UI/UX

#15 [feat] 삭제한 메이트 처리 로직 구현
  SniffMeet/SniffMeet/Source/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/PushNotification/PushNotificationRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/DeleteMateUseCase.swift
Labels: feature

#20 [fix] #17 다운스케일링시 프로필 이미지 메타데이타 보존
  SniffMeet/SniffMeet/Source/Common/Helper/ImageSampler.swift
Labels: bug fix

#24 [release] 240213
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SniffMeet.xcscheme
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog 1.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog 2.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog.png
Labels: release

#28 [release] dev와 병합
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SniffMeet.xcscheme
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog 1.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog 2.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog.png
Labels: release

#26 [feat] NearybyInteraction 없는 프로필 드랍 유즈케이스 구현
  SniffMeet/SNMSceneTests/LocalNetwork/MPCSessionConcurrencyTest.swift
  SniffMeet/SNMSceneTests/MateListScene/MateListInteractorTests.swift
  SniffMeet/SNMSceneTests/MateListScene/UseCaseMock.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SniffMeet/SniffMeet/Source/Core/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/UseCase/LocalNetworkUseCase/NearByProfileDropUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/LocalNetworkUseCase/TargetedProfileDropUseCase.swift
Labels: feature 🦖

#22 [UI] NI 지원 여부에 따른 프로필 드랍 뷰 구현
  SniffMeet/SNMSceneTests/MateListScene/MateListInteractorTests.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + GIFImageView.swift
  SniffMeet/SniffMeet/Source/Core/LocalNetwork/NI/NIDeviceChecker.swift
  SniffMeet/SniffMeet/Source/Mate/AddMate/Interactor/ProfileDropInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/AddMate/Presenter/ProfileDropPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/AddMate/Router/ProfileDropRouter.swift
  SniffMeet/SniffMeet/Source/Mate/AddMate/View/ConnectionState.swift
  SniffMeet/SniffMeet/Source/Mate/AddMate/View/ProfileDropViewController.swift
  SniffMeet/SniffMeet/Source/Scene/App/Routable.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Interactor/ProfileDropInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Presenter/ProfileDropPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Router/ProfileDropRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/View/ConnectionState.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/View/ProfileDropViewController.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/Scene/OnBoarding/MainBoarding/View/OnBoardingPageViewController.swift
Labels: UI/UX 🪄

#31 [feat] 알림 삭제 기능 구현
  SniffMeet/SNMSceneTests/MateListScene/RemoteDatabaseManagerMock.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + Date.swift
  SniffMeet/SniffMeet/Source/Core/Supabase/Database/SupabaseDBManager.swift
  SniffMeet/SniffMeet/Source/Core/Supabase/Database/SupabaseDBRequest.swift
  SniffMeet/SniffMeet/Source/Core/Supabase/Database/SupabaseDBRequestBuilder.swift
  SniffMeet/SniffMeet/Source/Entity/WalkNoti.swift
  SniffMeet/SniffMeet/Source/Scene/Home/Alarm/Interactor/NotificationListInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Home/Alarm/Presenter/NotificationListPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Home/Alarm/Router/NotificationListRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Home/Alarm/View/NotificationListViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/DeleteNotificationUseCase.swift
Labels: feature 🦖

#38 [feat] 프로필 드랍 뷰에 유즈케이스 적용
  SniffMeet/SNMSceneTests/MateListScene/UseCaseMock.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Core/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Interactor/ProfileDropInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Presenter/ProfileDropPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/Router/ProfileDropRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/View/ConnectionState.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/AddMate/View/ProfileDropViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/LocalNetworkUseCase/NearByProfileDropUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/LocalNetworkUseCase/TargetedProfileDropUseCase.swift
Labels: feature 🦖

#42 [feat] 산책 기록하는 뷰 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Design System/LayoutConstant.swift
  SniffMeet/SniffMeet/Source/Entity/WalkRoute.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Interactor/TrackWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Presenter/TrackWalkViewPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Router/TrackWalkRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/View/TrackWalkViewController.swift
Labels: feature 🦖, UI/UX 🪄

#46 [feat] 산책로그 기록을 위한 유즈케이스 작성
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Info.plist
  SniffMeet/SniffMeet/Source/Entity/WalkLog.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestUserLocationUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/UpdateUseCase/UpdateTimeUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/UpdateUseCase/UpdateUserLocationUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/UpdateUseCase/UpdateUserStepUseCase.swift
Labels: feature 🦖

#53 [feature] 산책로그 기록 측정하는 유즈케이즈 적용
  SniffMeet/SniffMeet/Source/Entity/WalkRoute.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Interactor/TrackWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Presenter/TrackWalkViewPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/Router/TrackWalkRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Walk/TrackWalk/View/TrackWalkViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/UpdateUseCase/UpdateTimeUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/UpdateUseCase/UpdateUserLocationUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/UpdateUseCase/UpdateUserStepUseCase.swift
Labels: feature 🦖

#44 [feat] ErrorHandler 구현
  .github/workflows/dev_test.yml
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/Common/Util/SNMErrorHandler.swift
  SniffMeet/SniffMeet/Source/Common/Util/SNMLogger.swift
  SniffMeet/SniffMeet/Source/Scene/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/Scene/App/SNMError.swift
  SniffMeet/SniffMeet/Source/Scene/Home/Alarm/Presenter/NotificationListPresenter.swift
  SniffMeet/SniffMeet/Source/Scene/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/CheckNicknameDuplicationUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestMateListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestNotiListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/DeleteMateUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/DeleteNotificationUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/RemoteSaveDeviceTokenUseCase.swift
Labels: feature 🦖, refactor

#50 [feature] 탭 바에 walk 탭 추가
  SniffMeet/SniffMeet/Resource/Assets.xcassets/custom.dog.fill.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/custom.dog.fill.imageset/custom.dog.fill.svg
  SniffMeet/SniffMeet/Source/Scene/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Scene/Tab/TabBarModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Scene/Tab/View/TabBarController.swift
Labels: feature 🦖, redesign
